<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php if(isset($title)) echo stripslashes($title); ?></title>
        <link rel="stylesheet" type="text/css" media="screen" href="/css/master_reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="/css/default.css" />
        <?php 
        loadComponent('StylesheetLoader');
        if(isset($css))
            linkStylesheets($css);
        ?>
        <script type="text/javascript" src="/js/jquery/jquery-1.9.1.min.js" ></script>
        <script type="text/javascript" src="/js/jquery/jquery-ui-1.10.0.custom.min.js"></script>
    </head>
    <body>
        <div align="center">
            <div class="envelope">
                <header>
                    Magesh Ravi's PHP Framework
                </header>
                <nav></nav>

                <?php echo $this->content; ?>

                <footer>
                    Copyrights &copy; 2011-2012 mageshravi
                </footer>
            </div>
        </div>
    </body>
</html>